language: cpp

git:
  submodules: false

env:
  global:
    - HUNTER_ROOT=${HOME}/hunter
    - GH_REPO_REF=github.com/ithron/CortidQCT.git
    - GH_REPO_NAME=CortidQCT
    - GENERATE_DOCS=no
    - Matlab_ROOT_DIR=${HOME}/MCR/v93
    - BUILD_MEX=OFF

cache:
  directories:
    - ${HUNTER_ROOT}

#################
# BUILD MATRIX
#
matrix:
  include:
    ##########
    # Linux

    ##########
    # GCC-7

    # Debug
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER=gcc GCC_VERSION=7
        - BUILD_TYPE=Debug

    # Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER=gcc GCC_VERSION=7
        - BUILD_TYPE=Release

    ##########
    # GCC-8

    # Debug
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - COMPILER=gcc GCC_VERSION=8
        - BUILD_TYPE=Debug

    # Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - COMPILER=gcc GCC_VERSION=8
        - BUILD_TYPE=Release

    ##############
    # Clang 4.0

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=4.0.0
        - BUILD_TYPE=Debug

    # Relase
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=4.0.0
        - BUILD_TYPE=Release

    ##############
    # Clang 5.0

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=5.0.2
        - BUILD_TYPE=Debug

    # Relase
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=5.0.2
        - BUILD_TYPE=Release

    ##############
    # Clang 6.0

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=6.0.1
        - BUILD_TYPE=Debug

    # Relase
    - os: linux
      addons:
        apt:
          packages:
            - doxygen doxygen-latex graphviz
      env:
        - COMPILER=clang CLANG_VERSION=6.0.1
        - BUILD_TYPE=Release
        - GENERATE_DOCS=yes

    ##########
    # macOS

    # Disabled until macOS 10.14 is available in travis.
    # Some C++17 features are not supported before 10.14,
    # independent of the xcode version.

    # ##############
    # # Xcode 10.0
    #
    # # Debug
    # - os: osx
    #   osx_image: xcode10
    #   env: BUILD_TYPE=Debug
    #
    # # Debug
    # - os: osx
    #   osx_image: xcode10
    #   env: BUILD_TYPE=Release

before_install:
  - |
    if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
          [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./scripts/setup-matlab.sh
      export BUILD_MEX=ON
    fi
  - source scripts/travis-toolchain.sh
  - git submodule update --init

script:
  - ./scripts/travis-cmake.sh
  - ./scripts/travis-build.sh

after_success:
  - |
    if [ "${GENERATE_DOCS}" = "yes" ]; then
      ./scripts/generateDocumentationAndDeploy.sh
    fi

deploy:
  provider: releases
  api_key: ${GH_REPO_TOKEN}
  file: CortidQCT-${TRAVIS_TAG}-x86_64-linux-gnu-ubuntu-18.04.tar.gz
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: "${BUILD_TYPE}" = "Release" -a "${COMPILER}" = "gcc" -a "${GCC_VERSION}" = "7"

