language: cpp

git:
  submodules: false

env:
  global:
    - HUNTER_ROOT=${HOME}/hunter

cache:
  directories:
    - ${HUNTER_ROOT}

#################
# BUILD MATRIX
#
matrix:
  include:
    ##########
    # Linux

    ##########
    # GCC-7

    # Debug
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_TYPE=Debug

    # Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_TYPE=Release

    ##########
    # GCC-8

    # Debug
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE=Debug

    # Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE=Release

    ##############
    # Clang 4.0

    # Debug
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-4.0.1"
        - BUILD_TYPE=Debug

    # Debug
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-4.0.1"
        - BUILD_TYPE=Release

    ##############
    # Clang 5.0

    # Debug
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-5.0.2"
        - BUILD_TYPE=Debug

    # Debug
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-5.0.2"
        - BUILD_TYPE=Release

    ##############
    # Clang 6.0

    # Debug
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-6.0.1"
        - BUILD_TYPE=Debug

    # Debug
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-6.0.1"
        - BUILD_TYPE=Release

    ##########
    # macOS

    ##############
    # Xcode 10.0

    # Debug
    - os: osx
      osx_image: xcode10
      env: BUILD_TYPE=Debug

    # Debug
    - os: osx
      osx_image: xcode10
      env: BUILD_TYPE=Release

before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init

before_script:
  - source script/travis-toolchain.sh

script:
  - ./scripts/travis-cmake.sh
  - ./scripts/travis-build.sh

