language: cpp

git:
  submodules: false

env:
  global:
    - HUNTER_ROOT=${HOME}/hunter

cache:
  directories:
    - ${HUNTER_ROOT}

#################
# BUILD MATRIX
#
matrix:
  include:
    ##########
    # Linux

    ##########
    # GCC-7

    # Debug
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER=gcc GCC_VERSION=7
        - BUILD_TYPE=Debug

    # Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER=gcc GCC_VERSION=7
        - BUILD_TYPE=Release

    ##########
    # GCC-8

    # Debug
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - COMPILER=gcc GCC_VERSION=8
        - BUILD_TYPE=Debug

    # Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - COMPILER=gcc GCC_VERSION=8
        - BUILD_TYPE=Release

    ##############
    # Clang 4.0

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=4.0.0
        - BUILD_TYPE=Debug

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=4.0.0
        - BUILD_TYPE=Release

    ##############
    # Clang 5.0

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=5.0.2
        - BUILD_TYPE=Debug

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=5.0.2
        - BUILD_TYPE=Release

    ##############
    # Clang 6.0

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=6.0.1
        - BUILD_TYPE=Debug

    # Debug
    - os: linux
      env:
        - COMPILER=clang CLANG_VERSION=6.0.1
        - BUILD_TYPE=Release

    ##########
    # macOS

    # Disabled until macOS 10.14 is available in travis.
    # Some C++17 features are not supported before 10.14, 
    # independent of the xcode version.

    # ##############
    # # Xcode 10.0
    #
    # # Debug
    # - os: osx
    #   osx_image: xcode10
    #   env: BUILD_TYPE=Debug
    #
    # # Debug
    # - os: osx
    #   osx_image: xcode10
    #   env: BUILD_TYPE=Release

before_install:
  - source scripts/travis-toolchain.sh
  - git submodule update --init

script:
  - ./scripts/travis-cmake.sh
  - ./scripts/travis-build.sh

