version: '1.0.{build}'

build:
    verbosity: detailed

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

environment:
  HUNTER_ROOT: C:\hunter
  CMAKE_OPTIONS: -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe
  GENERATOR: Ninja
  MAKE_PROGRAM: ninja
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache:
  - C:\hunter -> appveyor.yml

install:
  - git submodule update --init

build_script:
  - cmake -G "%GENERATOR%" %CMAKE_OPTIONS% "-DCMAKE_BUILD_TYPE=%configuration%" %APPVEYOR_BUILD_FOLDER%
  - "%MAKE_PROGRAM%"

test_script:
  - "%MAKE_PROGRAM% test"

on_failure:
  - appveyor PushArtifact CMakeFiles/CMakeOutput.log
  - appveyor PushArtifact CMakeFiles/CMakeError.log

artifacts:
  - path: '_build/CMakeFiles/*.log'
    name: logs

