version: '1.0.{build}'

build:
    verbosity: detailed

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

environment:
  HUNTER_ROOT: C:\hunter
  GENERATOR: Ninja
  MAKE_PROGRAM: ninja
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  MSVC_SETUP_ARG: x64
  USE_CLANG: ON
  CMAKE_OPTIONS: "-DCortidQCT_WITH_WERROR=OFF -DWITH_OPENCL=OFF"


cache:
  - C:\hunter -> appveyor.yml

init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: |
      net.exe user /add wtf "Asd4-asd47-BlaFoo23!" /Y
      net.exe localgroup administrators wtf /add


install:
  - call "%APPVEYOR_BUILD_FOLDER%\\appveyor-reqs-install.cmd"
  - git submodule update --init

before_build:
 - call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%

build_script:
  - IF DEFINED USE_CLANG set PATH="C:\Program Files\LLVM\bin";%PATH%
  - IF DEFINED USE_CLANG clang-cl -v
  - IF DEFINED USE_CLANG set CMAKE_EXTRA_OPTIONS="-DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe"
  - cmake -G "%GENERATOR%" %CMAKE_OPTIONS% -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_EXTRA_OPTIONS% %APPVEYOR_BUILD_FOLDER%
  - "%MAKE_PROGRAM%"

test_script:
  - "%MAKE_PROGRAM% test"

on_failure:
  - appveyor PushArtifact CMakeFiles/CMakeOutput.log
  - appveyor PushArtifact CMakeFiles/CMakeError.log

artifacts:
  - path: '_build/CMakeFiles/*.log'
    name: logs

