version: '1.2.1.{build}'

build:
    verbosity: detailed

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

environment:
  HUNTER_ROOT: C:\hunter
  GENERATOR: Ninja
  MAKE_PROGRAM: ninja
  MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  MSVC_SETUP_ARG: x64
  USE_CLANG: ON
  CMAKE_OPTIONS: "-DCortidQCT_WITH_WERROR=OFF -DWITH_OPENCL=OFF -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\\install"
  Matlab_ROOT_DIR: C:\Program Files\MATLAB\MATLAB Runtime\v93
  BUILD_MEX: OFF

cache:
  - C:\hunter

# init:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#   - ps: |
#       net.exe user /add wtf "Asd4-asd47-BlaFoo23!" /Y
#       net.exe localgroup administrators wtf /add


install:
  - call "%APPVEYOR_BUILD_FOLDER%\\scripts\\appveyor-reqs-install.cmd"
  - git submodule update --init

before_build:
 - call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%

build_script:
  - IF DEFINED USE_CLANG set PATH="C:\Program Files\LLVM\bin";%PATH%
  - IF DEFINED USE_CLANG clang-cl -v
  - IF DEFINED USE_CLANG set CC=clang-cl
  - IF DEFINED USE_CLANG set CXX=clang-cl
  - IF "%APPVEYOR_REPO_TAG%" == "true" ( set BUILD_MEX=ON )
  - cmake -G "%GENERATOR%" %CMAKE_OPTIONS% -DCMAKE_BUILD_TYPE=%configuration% -DBUILD_MEX=%BUILD_MEX% %APPVEYOR_BUILD_FOLDER%
  - "%MAKE_PROGRAM%"

test_script:
  - "%MAKE_PROGRAM% test"

on_failure:
  - appveyor PushArtifact CMakeFiles/CMakeOutput.log
  - appveyor PushArtifact CMakeFiles/CMakeError.log

on_success:
  - call "%APPVEYOR_BUILD_FOLDER%\\scripts\\appveyor-create-release.cmd"

